# Generated by Django 4.1.2 on 2024-06-23 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
        ('modeling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obsegmodel',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace'),
        ),
        migrations.DeleteModel(
            name='Workspace',
        ),
    ]
